name = "merc-verified"
version = "0.1.0"
defaultTargets = []

[[lean_lib]]
name = "MercVerified"

[[lean_lib]]
name = "Signatures"

[[lean_lib]]
name = "Code"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "232407ba9e7883e71aa57e046f130f52932fc9c8"

[[require]]
name = "aeneas"
path = "3rd-party/aeneas/backends/lean"