name = "merc-verified"
version = "0.1.0"
defaultTargets = ["MercVerified"]

[[lean_lib]]
name = "MercVerified"
globs = ["MercVerified.*"]

[[lean_lib]]
name = "Signatures"
globs = ["Signatures.*"]

[[lean_lib]]
name = "MachineNumbers"
globs = ["MachineNumbers.*"]

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.31.0"

[[require]]
name = "aeneas"
path = "3rd-party/aeneas/backends/lean"