name = "merc-verified"
version = "0.1.0"
defaultTargets = ["MercVerified"]

[[lean_lib]]
name = "MercVerified"
globs = ["MercVerified.*"]

[[lean_lib]]
name = "Signatures"
globs = ["Signatures.*"]

[[require]]
name = "cslib"
scope = "leanprover"
rev = "608cbe1b629a276abd3f2081f9b42dc766d8fd78"

[[require]]
name = "aeneas"
path = "3rd-party/aeneas/backends/lean"