-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import MercVerified.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open verified

/-- [core::borrow::{impl core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::hash::impls::{impl core::hash::Hash for usize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 813:16-813:56
    Name pattern: [core::hash::impls::{core::hash::Hash<usize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<usize>}::hash"]
axiom Usize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Usize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for (T, B)}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 894:20-894:60
    Name pattern: [core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash"]
axiom Pair.Insts.CoreHashHash.hash
  {T : Type} {B : Type} {S : Type} (HashInst : core.hash.Hash T) (HashInst1 :
  core.hash.Hash B) (HasherInst : core.hash.Hasher S) :
  (T × B) → S → Result S

/-- [core::slice::{[T]}::sort_unstable]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 3150:4-3152:15
    Name pattern: [core::slice::{[@T]}::sort_unstable]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::sort_unstable"]
axiom core.slice.Slice.sort_unstable
  {T : Type} (cmpOrdInst : core.cmp.Ord T) : Slice T → Result (Slice T)

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::ne]:
    Source: '/rustc/library/core/src/tuple.rs', lines 34:16-34:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne"]
axiom Pair.Insts.CoreCmpPartialEqPair.ne
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}::partial_cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 69:16-69:76
    Name pattern: [core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp"]
axiom Pair.Insts.CoreCmpPartialOrdPair.partial_cmp
  {U : Type} {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd U U)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  (U × T) → (U × T) → Result (Option Ordering)

/-- [core::tuple::{impl core::cmp::Ord for (U, T)}::cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 114:16-114:60
    Name pattern: [core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp"]
axiom Pair.Insts.CoreCmpOrd.cmp
  {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U) (cmpOrdInst1 :
  core.cmp.Ord T) :
  (U × T) → (U × T) → Result Ordering

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get_key_value]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1092:4-1095:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get_key_value]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get_key_value"]
axiom std.collections.hash.map.HashMap.get_key_value
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option (K × V))

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1332:4-1332:53
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert"]
axiom std.collections.hash.map.HashMap.insert
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.map.HashMap K V S A → K → V → Result ((Option V)
    × (std.collections.hash.map.HashMap K V S A))

/-- [std::collections::hash::map::{impl core::default::Default for std::collections::hash::map::HashMap<K, V, S, alloc::alloc::Global>}::default]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1494:4-1494:36
    Name pattern: [std::collections::hash::map::{core::default::Default<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>>}::default]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::default::Default<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>>}::default"]
axiom
  std.collections.hash.map.HashMapKVSGlobal.Insts.CoreDefaultDefault.default
  (K : Type) (V : Type) {S : Type} (coredefaultDefaultInst :
  core.default.Default S) :
  Result (std.collections.hash.map.HashMap K V S Global)

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::clear]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 539:4-539:27
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::clear]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::clear"]
axiom std.collections.hash.set.HashSet.clear
  {T : Type} {S : Type} {A : Type} :
  std.collections.hash.set.HashSet T S A → Result
    (std.collections.hash.set.HashSet T S A)

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::contains]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 806:4-809:21
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains"]
axiom std.collections.hash.set.HashSet.contains
  {T : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq T) (corehashHashInst : core.hash.Hash T)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow T Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.set.HashSet T S A → Q → Result Bool

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 1034:4-1034:46
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::insert"]
axiom std.collections.hash.set.HashSet.insert
  {T : Type} {S : Type} {A : Type} {Clause2_Hasher : Type} (corecmpEqInst :
  core.cmp.Eq T) (corehashHashInst : core.hash.Hash T) (corehashBuildHasherInst
  : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.set.HashSet T S A → T → Result (Bool ×
    (std.collections.hash.set.HashSet T S A))

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2901:4-2901:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3103:4-3103:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::clear]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::clear"]
axiom alloc.vec.Vec.clear
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3160:4-3160:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [alloc::vec::{alloc::vec::Vec<T>}::resize_with]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3255:4-3257:24
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::resize_with]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::resize_with"]
axiom alloc.vec.Vec.resize_with
  {T : Type} (A : Type) {F : Type} (coreopsfunctionFnMutFTupleTInst :
  core.ops.function.FnMut F Unit T) :
  alloc.vec.Vec T → Std.Usize → F → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::dedup]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3802:4-3802:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::dedup]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::dedup"]
axiom alloc.vec.Vec.dedup
  {T : Type} (A : Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::hash::Hash for alloc::vec::Vec<T>}::hash]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3965:4-3965:44
    Name pattern: [alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash]
    Visibility: public -/
@[rust_fun "alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash"]
axiom alloc.vec.Vec.Insts.CoreHashHash.hash
  {T : Type} (A : Type) {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  alloc.vec.Vec T → H → Result H

/-- [alloc::vec::{impl core::iter::traits::collect::Extend<T> for alloc::vec::Vec<T>}::extend]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4107:4-4107:60
    Name pattern: [alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend"]
axiom alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend.extend
  {T : Type} (A : Type) {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorInst :
  core.iter.traits.collect.IntoIterator I T Clause0_IntoIter) :
  alloc.vec.Vec T → I → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::default::Default for alloc::vec::Vec<T>}::default]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4417:4-4417:26
    Name pattern: [alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default"]
axiom alloc.vec.Vec.Insts.CoreDefaultDefault.default
  (T : Type) : Result (alloc.vec.Vec T)

/-- [merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<T>}::index]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 98:4-98:42
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<@T>}::index]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<@T>}::index"]
axiom merc_collections.compressed_vec.ByteCompressedVec.index
  {T : Type} (CompressedEntryInst :
  merc_collections.compressed_vec.CompressedEntry T) :
  merc_collections.compressed_vec.ByteCompressedVec T → Std.Usize → Result
    T

/-- [merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<T>}::len]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 118:4-118:30
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<@T>}::len]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::ByteCompressedVec<@T>}::len"]
axiom merc_collections.compressed_vec.ByteCompressedVec.len
  {T : Type} (CompressedEntryInst :
  merc_collections.compressed_vec.CompressedEntry T) :
  merc_collections.compressed_vec.ByteCompressedVec T → Result Std.Usize

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for usize}::bytes_required]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 496:4-496:37
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::bytes_required]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::bytes_required"]
axiom Usize.Insts.Merc_collectionsCompressed_vecCompressedEntry.bytes_required
  : Std.Usize → Result Std.Usize

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for usize}::from_bytes]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 488:4-488:39
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::from_bytes]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::from_bytes"]
axiom Usize.Insts.Merc_collectionsCompressed_vecCompressedEntry.from_bytes
  : Slice Std.U8 → Result Std.Usize

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for usize}::to_bytes]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 481:4-481:40
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::to_bytes]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<usize>}::to_bytes"]
axiom Usize.Insts.Merc_collectionsCompressed_vecCompressedEntry.to_bytes
  : Std.Usize → Slice Std.U8 → Result (Slice Std.U8)

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for merc_utilities::tagged_index::TagIndex<T, Tag>}::from_bytes]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 519:4-519:39
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::from_bytes]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::from_bytes"]
axiom
  merc_utilities.tagged_index.TagIndex.Insts.Merc_collectionsCompressed_vecCompressedEntry.from_bytes
  {T : Type} (Tag : Type) (CompressedEntryInst :
  merc_collections.compressed_vec.CompressedEntry T) (coremarkerCopyInst :
  core.marker.Copy T) :
  Slice Std.U8 → Result (merc_utilities.tagged_index.TagIndex T Tag)

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for merc_utilities::tagged_index::TagIndex<T, Tag>}::bytes_required]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 515:12-515:45
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::bytes_required]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::bytes_required"]
axiom
  merc_utilities.tagged_index.TagIndex.Insts.Merc_collectionsCompressed_vecCompressedEntry.bytes_required
  {T : Type} {Tag : Type} (CompressedEntryInst :
  merc_collections.compressed_vec.CompressedEntry T) (coremarkerCopyInst :
  core.marker.Copy T) :
  merc_utilities.tagged_index.TagIndex T Tag → Result Std.Usize

/-- [merc_collections::compressed_vec::{impl merc_collections::compressed_vec::CompressedEntry for merc_utilities::tagged_index::TagIndex<T, Tag>}::to_bytes]:
    Source: '3rd-party/merc/crates/collections/src/compressed_vec.rs', lines 514:12-514:48
    Name pattern: [merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::to_bytes]
    Visibility: public -/
@[rust_fun
  "merc_collections::compressed_vec::{merc_collections::compressed_vec::CompressedEntry<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::to_bytes"]
axiom
  merc_utilities.tagged_index.TagIndex.Insts.Merc_collectionsCompressed_vecCompressedEntry.to_bytes
  {T : Type} {Tag : Type} (CompressedEntryInst :
  merc_collections.compressed_vec.CompressedEntry T) (coremarkerCopyInst :
  core.marker.Copy T) :
  merc_utilities.tagged_index.TagIndex T Tag → Slice Std.U8 → Result (Slice
    Std.U8)

/-- [merc_io::progress::{merc_io::progress::TimeProgress<T>}::print]:
    Source: '3rd-party/merc/crates/io/src/progress.rs', lines 38:4-38:34
    Name pattern: [merc_io::progress::{merc_io::progress::TimeProgress<@T>}::print]
    Visibility: public -/
@[rust_fun "merc_io::progress::{merc_io::progress::TimeProgress<@T>}::print"]
axiom merc_io.progress.TimeProgress.print
  {T : Type} : merc_io.progress.TimeProgress T → T → Result Unit

/-- [merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent]:
    Source: '3rd-party/merc/crates/reduction/src/block_partition.rs', lines 532:4-532:31
    Name pattern: [merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent] -/
@[rust_fun
  "merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent"]
axiom merc_reduction.block_partition.Block.assert_consistent
  : merc_reduction.block_partition.Block → Result Unit

/-- [merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent]:
    Source: '3rd-party/merc/crates/reduction/src/block_partition.rs', lines 955:4-955:39
    Name pattern: [merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent] -/
@[rust_fun
  "merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent"]
axiom merc_reduction.block_partition.BlockPartition.assert_consistent
  : merc_reduction.block_partition.BlockPartition → Result Bool

/-- [merc_utilities::timing::{merc_utilities::timing::Timing}::measure]:
    Source: '3rd-party/merc/crates/utilities/src/timing.rs', lines 37:4-39:25
    Name pattern: [merc_utilities::timing::{merc_utilities::timing::Timing}::measure]
    Visibility: public -/
@[rust_fun "merc_utilities::timing::{merc_utilities::timing::Timing}::measure"]
axiom merc_utilities.timing.Timing.measure
  {F : Type} {O : Type} (coreopsfunctionFnOnceFTupleOInst :
  core.ops.function.FnOnce F Unit O) :
  merc_utilities.timing.Timing → Str → F → Result O

/-- [rustc_hash::{impl core::default::Default for rustc_hash::FxBuildHasher}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 344:44-344:51
    Name pattern: [rustc_hash::{core::default::Default<rustc_hash::FxBuildHasher>}::default]
    Visibility: public -/
@[rust_fun
  "rustc_hash::{core::default::Default<rustc_hash::FxBuildHasher>}::default"]
axiom rustc_hash.FxBuildHasher.Insts.CoreDefaultDefault.default
  : Result rustc_hash.FxBuildHasher

/-- [rustc_hash::{impl core::hash::BuildHasher<rustc_hash::FxHasher> for rustc_hash::FxBuildHasher}::build_hasher]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 350:4-350:38
    Name pattern: [rustc_hash::{core::hash::BuildHasher<rustc_hash::FxBuildHasher, rustc_hash::FxHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "rustc_hash::{core::hash::BuildHasher<rustc_hash::FxBuildHasher, rustc_hash::FxHasher>}::build_hasher"]
axiom rustc_hash.FxBuildHasher.Insts.CoreHashBuildHasherFxHasher.build_hasher
  : rustc_hash.FxBuildHasher → Result rustc_hash.FxHasher

/-- [rustc_hash::{impl core::hash::Hasher for rustc_hash::FxHasher}::finish]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 192:4-192:27
    Name pattern: [rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::finish]
    Visibility: public -/
@[rust_fun "rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::finish"]
axiom rustc_hash.FxHasher.Insts.CoreHashHasher.finish
  : rustc_hash.FxHasher → Result Std.U64

/-- [rustc_hash::{impl core::hash::Hasher for rustc_hash::FxHasher}::write]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 130:4-130:37
    Name pattern: [rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::write]
    Visibility: public -/
@[rust_fun "rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::write"]
axiom rustc_hash.FxHasher.Insts.CoreHashHasher.write
  : rustc_hash.FxHasher → Slice Std.U8 → Result rustc_hash.FxHasher

/-- [merc_utilities::tagged_index::{impl core::hash::Hash for merc_utilities::tagged_index::TagIndex<T, Tag>}::hash]:
    Source: '3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 83:4-83:55
    Name pattern: [merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash.hash
  {T : Type} {Tag : Type} {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  merc_utilities.tagged_index.TagIndex T Tag → H → Result H

/-- [merc_reduction::signature_refinement::new_worklist_progress]:
    Source: '3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 1655:0-1655:58
    Name pattern: [merc_reduction::signature_refinement::new_worklist_progress] -/
@[rust_fun "merc_reduction::signature_refinement::new_worklist_progress"]
axiom merc_reduction.signature_refinement.new_worklist_progress
  : Result (merc_io.progress.TimeProgress (Std.Usize × Std.Usize))

