-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: function definitions
import Aeneas
import MercVerified.Code.Types
import MercVerified.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace verified

/-- Trait implementation: [core::borrow::{core::borrow::Borrow<T> for T}]
    Source: '/rustc/library/core/src/borrow.rs', lines 212:0-212:37
    Name pattern: [core::borrow::Borrow<@T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<@T, @T>"]
def core.borrow.Borrow.Blanket (T : Type) : core.borrow.Borrow T T := {
  borrow := core.borrow.Borrow.Blanket.borrow
}

/-- Trait implementation: [core::hash::impls::{core::hash::Hash for usize}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 810:12-810:29
    Name pattern: [core::hash::Hash<usize>] -/
@[reducible, rust_trait_impl "core::hash::Hash<usize>"]
def Usize.Insts.CoreHashHash : core.hash.Hash Std.Usize := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    Usize.Insts.CoreHashHash.hash HasherInst
}

/-- Trait implementation: [core::iter::traits::accum::{core::iter::traits::accum::Sum<usize> for usize}]
    Source: '/rustc/library/core/src/iter/traits/accum.rs', lines 48:8-48:23
    Name pattern: [core::iter::traits::accum::Sum<usize, usize>] -/
@[reducible, rust_trait_impl "core::iter::traits::accum::Sum<usize, usize>"]
def Usize.Insts.CoreIterTraitsAccumSumUsize : core.iter.traits.accum.Sum
  Std.Usize Std.Usize := {
  sum := fun {I : Type} (iteratorIteratorPUsizeInst :
    core.iter.traits.iterator.Iterator I Std.Usize) =>
    Usize.Insts.CoreIterTraitsAccumSumUsize.sum iteratorIteratorPUsizeInst
}

/-- Trait implementation: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2232:0-2232:44
    Name pattern: [core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>"]
def
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV
  (K : Type) (V : Type) : core.iter.traits.iterator.Iterator
  (std.collections.hash.map.Values K V) V := {
  next :=
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.next
  map := fun {B : Type} {F : Type} (coreopsfunctionFnMutPTupleSharedFPInst :
    core.ops.function.FnMut F V B) =>
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.map
    coreopsfunctionFnMutPTupleSharedFPInst
  collect := fun {B : Type} (coreitertraitscollectFromIteratorPSharedPInst :
    core.iter.traits.collect.FromIterator B V) =>
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.collect
    coreitertraitscollectFromIteratorPSharedPInst
  sum := fun {S : Type} (coreitertraitsaccumSumPSharedPInst :
    core.iter.traits.accum.Sum S V) =>
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.sum
    coreitertraitsaccumSumPSharedPInst
}

/-- Trait implementation: [std::hash::random::{core::clone::Clone for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 34:9-34:14
    Name pattern: [core::clone::Clone<std::hash::random::RandomState>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<std::hash::random::RandomState>"]
def std.hash.random.RandomState.Insts.CoreCloneClone : core.clone.Clone
  std.hash.random.RandomState := {
  clone := std.hash.random.RandomState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 125:0-125:29
    Name pattern: [core::hash::Hasher<std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::Hasher<std::hash::random::DefaultHasher>"]
def std.hash.random.DefaultHasher.Insts.CoreHashHasher : core.hash.Hasher
  std.hash.random.DefaultHasher := {
  finish := std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  write := std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
}

/-- Trait implementation: [std::hash::random::{core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 80:0-80:32
    Name pattern: [core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>"]
def std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher :
  core.hash.BuildHasher std.hash.random.RandomState
  std.hash.random.DefaultHasher := {
  HasherInst := std.hash.random.DefaultHasher.Insts.CoreHashHasher
  build_hasher :=
    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
}

/-- Trait implementation: [merc_lts::lts::{core::clone::Clone for merc_lts::lts::Transition}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 115:9-115:14
    Name pattern: [core::clone::Clone<merc_lts::lts::Transition>] -/
@[reducible, rust_trait_impl "core::clone::Clone<merc_lts::lts::Transition>"]
def merc_lts.lts.Transition.Insts.CoreCloneClone : core.clone.Clone
  merc_lts.lts.Transition := {
  clone := merc_lts.lts.Transition.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition> for merc_lts::lts::Transition}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 115:23-115:32
    Name pattern: [core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>"]
def merc_lts.lts.Transition.Insts.CoreCmpPartialEqTransition :
  core.cmp.PartialEq merc_lts.lts.Transition merc_lts.lts.Transition := {
  eq := merc_lts.lts.Transition.Insts.CoreCmpPartialEqTransition.eq
}

/-- Trait implementation: [merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<T, Tag>> for merc_utilities::tagged_index::TagIndex<T, Tag>}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 58:0-58:54
    Name pattern: [core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, merc_utilities::tagged_index::TagIndex<@T, @Tag>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, merc_utilities::tagged_index::TagIndex<@T, @Tag>>"]
def merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEqTagIndex {T :
  Type} (Tag : Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (merc_utilities.tagged_index.TagIndex T Tag)
  (merc_utilities.tagged_index.TagIndex T Tag) := {
  eq := merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEqTagIndex.eq
    corecmpPartialEqInst
}

/-- Trait implementation: [merc_utilities::tagged_index::{core::cmp::Eq for merc_utilities::tagged_index::TagIndex<T, Tag>}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 56:0-56:47
    Name pattern: [core::cmp::Eq<merc_utilities::tagged_index::TagIndex<@T, @Tag>>] -/
@[reducible, rust_trait_impl
  "core::cmp::Eq<merc_utilities::tagged_index::TagIndex<@T, @Tag>>"]
def merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq {T : Type} (Tag :
  Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) : core.cmp.Eq
  (merc_utilities.tagged_index.TagIndex T Tag) := {
  partialEqInst :=
    merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEqTagIndex Tag
    corecmpPartialEqInst
  assert_receiver_is_total_eq :=
    merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq.assert_receiver_is_total_eq
    corecmpPartialEqInst
}

/-- Trait implementation: [merc_utilities::tagged_index::{core::hash::Hash for merc_utilities::tagged_index::TagIndex<T, Tag>}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 76:0-76:44
    Name pattern: [core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>] -/
@[reducible, rust_trait_impl
  "core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>"]
def merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash {T : Type} (Tag :
  Type) (corehashHashInst : core.hash.Hash T) : core.hash.Hash
  (merc_utilities.tagged_index.TagIndex T Tag) := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash.hash
    corehashHashInst corehashHasherInst
}

/-- Trait implementation: [merc_utilities::tagged_index::{core::clone::Clone for merc_utilities::tagged_index::TagIndex<T, Tag>}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 82:0-82:46
    Name pattern: [core::clone::Clone<merc_utilities::tagged_index::TagIndex<@T, @Tag>>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<merc_utilities::tagged_index::TagIndex<@T, @Tag>>"]
def merc_utilities.tagged_index.TagIndex.Insts.CoreCloneClone {T : Type} (Tag :
  Type) (corecloneCloneInst : core.clone.Clone T) : core.clone.Clone
  (merc_utilities.tagged_index.TagIndex T Tag) := {
  clone := merc_utilities.tagged_index.TagIndex.Insts.CoreCloneClone.clone
    corecloneCloneInst
}

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::marker::StructuralPartialEq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 18:9-18:18 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreMarkerStructuralPartialEq
  (Label : Type) : core.marker.StructuralPartialEq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
}

/-- [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 18:9-18:18
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem.eq
  {Label : Type} (corecmpPartialEqInst : core.cmp.PartialEq Label Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label)
  (other : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Bool
  := do
  let b ←
    std.collections.hash.map.HashMap.Insts.CoreCmpPartialEqHashMap.eq
      (merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq
      merc_lts.lts.StateTag core.cmp.PartialEqUsize)
      (merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash
      merc_lts.lts.StateTag Usize.Insts.CoreHashHash) (core.cmp.PartialEqVec
      merc_lts.lts.Transition.Insts.CoreCmpPartialEqTransition)
      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
      self.transitions other.transitions
  if b
  then
    let b1 ←
      alloc.vec.partial_eq.PartialEqVec.eq corecmpPartialEqInst self.labels
        other.labels
    if b1
    then
      merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEqTagIndex.eq
        core.cmp.PartialEqUsize self.initial_state other.initial_state
    else ok false
  else ok false

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 18:9-18:18 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem
  {Label : Type} (corecmpPartialEqInst : core.cmp.PartialEq Label Label) :
  core.cmp.PartialEq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label)
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  eq :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem.eq
    corecmpPartialEqInst
}

/-- [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::assert_receiver_is_total_eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 18:20-18:22
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq.assert_receiver_is_total_eq
  {Label : Type} (corecmpEqInst : core.cmp.Eq Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 18:20-18:22 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq
  {Label : Type} (corecmpEqInst : core.cmp.Eq Label) : core.cmp.Eq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  partialEqInst :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem
    corecmpEqInst.partialEqInst
  assert_receiver_is_total_eq :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq.assert_receiver_is_total_eq
    corecmpEqInst
}

/-- [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::clone]:
    Source: 'src/simple_labelled_transition_system.rs', lines 18:24-18:29
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone.clone
  {Label : Type} (corecloneCloneInst : core.clone.Clone Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (simple_labelled_transition_system.SimpleLabelledTransitionSystem
    Label)
  := do
  let hm ←
    std.collections.hash.map.HashMap.Insts.CoreCloneClone.clone
      (merc_utilities.tagged_index.TagIndex.Insts.CoreCloneClone
      merc_lts.lts.StateTag core.clone.CloneUsize) (core.clone.CloneallocvecVec
      merc_lts.lts.Transition.Insts.CoreCloneClone)
      std.hash.random.RandomState.Insts.CoreCloneClone
      core.core.clone.CloneGlobal self.transitions
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.labels
  let ti ←
    merc_utilities.tagged_index.TagIndex.Insts.CoreCloneClone.clone
      core.clone.CloneUsize self.initial_state
  ok { transitions := hm, labels := v, initial_state := ti }

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 18:24-18:29 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone
  {Label : Type} (corecloneCloneInst : core.clone.Clone Label) :
  core.clone.Clone
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  clone :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone.clone
    corecloneCloneInst
}

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::merge_disjoint]:
    Source: 'src/simple_labelled_transition_system.rs', lines 68:4-76:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.merge_disjoint
  {Label : Type} {L : Type} (merc_ltsltsTransitionLabelInst :
  merc_lts.lts.TransitionLabel Label) (merc_ltsltsLTSInst : merc_lts.lts.LTS L
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) (_other : L) :
  Result ((merc_lts.labelled_transition_system.LabelledTransitionSystem Label)
    × (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag))
  := do
  fail panic

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::is_hidden_label]:
    Source: 'src/simple_labelled_transition_system.rs', lines 64:4-66:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.is_hidden_label
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label)
  (label_index : merc_utilities.tagged_index.TagIndex Std.Usize
  merc_lts.lts.LabelTag) :
  Result Bool
  := do
  merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEq.eq
    core.cmp.PartialEqUsize label_index 0#usize

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::labels]:
    Source: 'src/simple_labelled_transition_system.rs', lines 60:4-62:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.labels
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (Slice Label)
  := do
  alloc.vec.Vec.index (core.slice.index.SliceIndexRangeFromUsizeSlice Label)
    self.labels { start := 0#usize }

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnMut<(&'_ (alloc::vec::Vec<merc_lts::lts::Transition>)), usize> for verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}::call_mut]:
    Source: 'src/simple_labelled_transition_system.rs', lines 57:38-57:49 -/
def
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (c :
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure
  Label) (tupled_args : alloc.vec.Vec merc_lts.lts.Transition) :
  Result (Std.Usize ×
    (simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure
    Label))
  := do
  let i := alloc.vec.Vec.len tupled_args
  ok (i, c)

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnOnce<(&'_ (alloc::vec::Vec<merc_lts::lts::Transition>)), usize> for verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}::call_once]:
    Source: 'src/simple_labelled_transition_system.rs', lines 57:38-57:49 -/
def
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize.call_once
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (c :
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure
  Label) (v : alloc.vec.Vec merc_lts.lts.Transition) :
  Result Std.Usize
  := do
  let (i, _) ←
    simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
      merc_ltsltsTransitionLabelInst c v
  ok i

/-- Trait implementation: [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnOnce<(&'_ (alloc::vec::Vec<merc_lts::lts::Transition>)), usize> for verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 57:38-57:49 -/
@[reducible]
def
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label) : core.ops.function.FnOnce
  (simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure
  Label) (alloc.vec.Vec merc_lts.lts.Transition) Std.Usize := {
  call_once :=
    simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize.call_once
    merc_ltsltsTransitionLabelInst
}

/-- Trait implementation: [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnMut<(&'_ (alloc::vec::Vec<merc_lts::lts::Transition>)), usize> for verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 57:38-57:49 -/
@[reducible]
def
  simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label) : core.ops.function.FnMut
  (simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure
  Label) (alloc.vec.Vec merc_lts.lts.Transition) Std.Usize := {
  FnOnceInst :=
    simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize
    merc_ltsltsTransitionLabelInst
  call_mut :=
    simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
    merc_ltsltsTransitionLabelInst
}

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions]:
    Source: 'src/simple_labelled_transition_system.rs', lines 56:4-58:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_transitions
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  let v ← std.collections.hash.map.HashMap.values self.transitions
  let m ←
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.map
      (simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
      merc_ltsltsTransitionLabelInst) v ()
  core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.sum
    (std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV
    (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag)
    (alloc.vec.Vec merc_lts.lts.Transition))
    (simple_labelled_transition_system.LTSSimpleLabelledTransitionSystemLabel.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
    merc_ltsltsTransitionLabelInst) Usize.Insts.CoreIterTraitsAccumSumUsize m

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_labels]:
    Source: 'src/simple_labelled_transition_system.rs', lines 52:4-54:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_labels
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  ok (alloc.vec.Vec.len self.labels)

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_states]:
    Source: 'src/simple_labelled_transition_system.rs', lines 48:4-50:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_states
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  std.collections.hash.map.HashMap.len self.transitions

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::iter_states]:
    Source: 'src/simple_labelled_transition_system.rs', lines 44:4-46:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.iter_states
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag))
  := do
  let i ←
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_states
      merc_ltsltsTransitionLabelInst self
  let m ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.map
      core.iter.range.StepUsize (BuiltinFnMut Std.Usize
      (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag))
      { start := 0#usize, «end» := i }
      (merc_utilities.tagged_index.TagIndex.new merc_lts.lts.StateTag)
  core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
    (core.iter.traits.iterator.IteratorRange core.iter.range.StepUsize)
    (BuiltinFnMut Std.Usize (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag)) (core.iter.traits.collect.FromIteratorVec
    (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag)) m

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::initial_state_index]:
    Source: 'src/simple_labelled_transition_system.rs', lines 40:4-42:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.initial_state_index
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag)
  := do
  ok self.initial_state

/-- [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::outgoing_transitions]:
    Source: 'src/simple_labelled_transition_system.rs', lines 33:4-38:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.outgoing_transitions
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label)
  (state_index : merc_utilities.tagged_index.TagIndex Std.Usize
  merc_lts.lts.StateTag) :
  Result (alloc.vec.Vec merc_lts.lts.Transition)
  := do
  let o ←
    std.collections.hash.map.HashMap.get
      (merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq
      merc_lts.lts.StateTag core.cmp.PartialEqUsize)
      (merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash
      merc_lts.lts.StateTag Usize.Insts.CoreHashHash)
      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
      (core.borrow.Borrow.Blanket (merc_utilities.tagged_index.TagIndex
      Std.Usize merc_lts.lts.StateTag))
      (merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash
      merc_lts.lts.StateTag Usize.Insts.CoreHashHash)
      (merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq
      merc_lts.lts.StateTag core.cmp.PartialEqUsize) self.transitions
      state_index
  let v ← core.option.Option.expect o (toStr "State index out of bounds.")
  alloc.vec.CloneVec.clone merc_lts.lts.Transition.Insts.CoreCloneClone v

/-- Trait implementation: [verified::simple_labelled_transition_system::{merc_lts::lts::LTS<Label> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 30:0-77:1 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS
  {Label : Type} (merc_ltsltsTransitionLabelInst : merc_lts.lts.TransitionLabel
  Label) : merc_lts.lts.LTS
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label)
  Label := {
  TransitionLabelInst := merc_ltsltsTransitionLabelInst
  initial_state_index :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.initial_state_index
    merc_ltsltsTransitionLabelInst
  outgoing_transitions :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.outgoing_transitions
    merc_ltsltsTransitionLabelInst
  iter_states :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.iter_states
    merc_ltsltsTransitionLabelInst
  num_of_states :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_states
    merc_ltsltsTransitionLabelInst
  num_of_labels :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_labels
    merc_ltsltsTransitionLabelInst
  num_of_transitions :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.num_of_transitions
    merc_ltsltsTransitionLabelInst
  labels :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.labels
    merc_ltsltsTransitionLabelInst
  is_hidden_label :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.is_hidden_label
    merc_ltsltsTransitionLabelInst
  merge_disjoint := fun {L : Type} (merc_ltsltsLTSInst : merc_lts.lts.LTS L
    Label) =>
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.Merc_ltsLtsLTS.merge_disjoint
    merc_ltsltsTransitionLabelInst merc_ltsltsLTSInst
}

end verified
