-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import MercVerified.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open verified

/-- [core::borrow::{impl core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::hash::impls::{impl core::hash::Hash for usize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 813:16-813:56
    Name pattern: [core::hash::impls::{core::hash::Hash<usize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<usize>}::hash"]
axiom Usize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Usize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for (T, B)}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 894:20-894:60
    Name pattern: [core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<(@T, @B)>}::hash"]
axiom Pair.Insts.CoreHashHash.hash
  {T : Type} {B : Type} {S : Type} (HashInst : core.hash.Hash T) (HashInst1 :
  core.hash.Hash B) (HasherInst : core.hash.Hasher S) :
  (T × B) → S → Result S

/-- [core::slice::{[T]}::sort_unstable]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 3150:4-3152:15
    Name pattern: [core::slice::{[@T]}::sort_unstable]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::sort_unstable"]
axiom core.slice.Slice.sort_unstable
  {T : Type} (cmpOrdInst : core.cmp.Ord T) : Slice T → Result (Slice T)

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::ne]:
    Source: '/rustc/library/core/src/tuple.rs', lines 34:16-34:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::ne"]
axiom Pair.Insts.CoreCmpPartialEqPair.ne
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}::eq]:
    Source: '/rustc/library/core/src/tuple.rs', lines 30:16-30:55
    Name pattern: [core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::PartialEq<(@U, @T), (@U, @T)>}::eq"]
axiom Pair.Insts.CoreCmpPartialEqPair.eq
  {U : Type} {T : Type} (cmpPartialEqInst : core.cmp.PartialEq U U)
  (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  (U × T) → (U × T) → Result Bool

/-- [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}::partial_cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 69:16-69:76
    Name pattern: [core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::tuple::{core::cmp::PartialOrd<(@U, @T), (@U, @T)>}::partial_cmp"]
axiom Pair.Insts.CoreCmpPartialOrdPair.partial_cmp
  {U : Type} {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd U U)
  (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  (U × T) → (U × T) → Result (Option Ordering)

/-- [core::tuple::{impl core::cmp::Ord for (U, T)}::cmp]:
    Source: '/rustc/library/core/src/tuple.rs', lines 114:16-114:60
    Name pattern: [core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp]
    Visibility: public -/
@[rust_fun "core::tuple::{core::cmp::Ord<(@U, @T)>}::cmp"]
axiom Pair.Insts.CoreCmpOrd.cmp
  {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U) (cmpOrdInst1 :
  core.cmp.Ord T) :
  (U × T) → (U × T) → Result Ordering

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::values]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 576:4-576:44
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::values]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::values"]
axiom std.collections.hash.map.HashMap.values
  {K : Type} {V : Type} {S : Type} {A : Type} :
  std.collections.hash.map.HashMap K V S A → Result
    (std.collections.hash.map.Values K V)

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::len]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 727:4-727:30
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::len]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::len"]
axiom std.collections.hash.map.HashMap.len
  {K : Type} {V : Type} {S : Type} {A : Type} :
  std.collections.hash.map.HashMap K V S A → Result Std.Usize

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1034:4-1037:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get"]
axiom std.collections.hash.map.HashMap.get
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option V)

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get_key_value]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1092:4-1095:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get_key_value]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get_key_value"]
axiom std.collections.hash.map.HashMap.get_key_value
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option (K × V))

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1332:4-1332:53
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::insert"]
axiom std.collections.hash.map.HashMap.insert
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.map.HashMap K V S A → K → V → Result ((Option V)
    × (std.collections.hash.map.HashMap K V S A))

/-- [std::collections::hash::map::{impl core::clone::Clone for std::collections::hash::map::HashMap<K, V, S, A>}::clone]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1437:4-1437:27
    Name pattern: [std::collections::hash::map::{core::clone::Clone<std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::clone]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::clone::Clone<std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::clone"]
axiom std.collections.hash.map.HashMap.Insts.CoreCloneClone.clone
  {K : Type} {V : Type} {S : Type} {A : Type} (corecloneCloneInst :
  core.clone.Clone K) (corecloneCloneInst1 : core.clone.Clone V)
  (corecloneCloneInst2 : core.clone.Clone S) (corecloneCloneInst3 :
  core.clone.Clone A) :
  std.collections.hash.map.HashMap K V S A → Result
    (std.collections.hash.map.HashMap K V S A)

/-- [std::collections::hash::map::{impl core::cmp::PartialEq<std::collections::hash::map::HashMap<K, V, S, A>> for std::collections::hash::map::HashMap<K, V, S, A>}::eq]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1455:4-1455:53
    Name pattern: [std::collections::hash::map::{core::cmp::PartialEq<std::collections::hash::map::HashMap<@K, @V, @S, @A>, std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::eq]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::cmp::PartialEq<std::collections::hash::map::HashMap<@K, @V, @S, @A>, std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::eq"]
axiom std.collections.hash.map.HashMap.Insts.CoreCmpPartialEqHashMap.eq
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause3_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corecmpPartialEqInst : core.cmp.PartialEq V V) (corehashBuildHasherInst :
  core.hash.BuildHasher S Clause3_Hasher) :
  std.collections.hash.map.HashMap K V S A → std.collections.hash.map.HashMap
    K V S A → Result Bool

/-- [std::collections::hash::map::{impl core::default::Default for std::collections::hash::map::HashMap<K, V, S, alloc::alloc::Global>}::default]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1494:4-1494:36
    Name pattern: [std::collections::hash::map::{core::default::Default<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>>}::default]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::default::Default<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>>}::default"]
axiom
  std.collections.hash.map.HashMapKVSGlobal.Insts.CoreDefaultDefault.default
  (K : Type) (V : Type) {S : Type} (coredefaultDefaultInst :
  core.default.Default S) :
  Result (std.collections.hash.map.HashMap K V S Global)

/-- [std::collections::hash::map::{impl core::iter::traits::iterator::Iterator<&'a V> for std::collections::hash::map::Values<'a, K, V>}::next]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2264:4-2264:39
    Name pattern: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::next]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::next"]
axiom
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.next
  {K : Type} {V : Type} :
  std.collections.hash.map.Values K V → Result ((Option V) ×
    (std.collections.hash.map.Values K V))

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::clear]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 539:4-539:27
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::clear]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::clear"]
axiom std.collections.hash.set.HashSet.clear
  {T : Type} {S : Type} {A : Type} :
  std.collections.hash.set.HashSet T S A → Result
    (std.collections.hash.set.HashSet T S A)

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::contains]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 806:4-809:21
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::contains"]
axiom std.collections.hash.set.HashSet.contains
  {T : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq T) (corehashHashInst : core.hash.Hash T)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow T Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.set.HashSet T S A → Q → Result Bool

/-- [std::collections::hash::set::{std::collections::hash::set::HashSet<T, S, A>}::insert]:
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 1034:4-1034:46
    Name pattern: [std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::insert]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::set::{std::collections::hash::set::HashSet<@T, @S, @A>}::insert"]
axiom std.collections.hash.set.HashSet.insert
  {T : Type} {S : Type} {A : Type} {Clause2_Hasher : Type} (corecmpEqInst :
  core.cmp.Eq T) (corehashHashInst : core.hash.Hash T) (corehashBuildHasherInst
  : core.hash.BuildHasher S Clause2_Hasher) :
  std.collections.hash.set.HashSet T S A → T → Result (Bool ×
    (std.collections.hash.set.HashSet T S A))

/-- [std::hash::random::{impl core::clone::Clone for std::hash::random::RandomState}::clone]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 34:9-34:14
    Name pattern: [std::hash::random::{core::clone::Clone<std::hash::random::RandomState>}::clone]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::clone::Clone<std::hash::random::RandomState>}::clone"]
axiom std.hash.random.RandomState.Insts.CoreCloneClone.clone
  : std.hash.random.RandomState → Result std.hash.random.RandomState

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::finish]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 140:4-140:27
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  : std.hash.random.DefaultHasher → Result Std.U64

/-- [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}::write]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 130:4-130:35
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
  :
  std.hash.random.DefaultHasher → Slice Std.U8 → Result
    std.hash.random.DefaultHasher

/-- [std::hash::random::{impl core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}::build_hasher]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 83:4-83:43
    Name pattern: [std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher"]
axiom
  std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
  : std.hash.random.RandomState → Result std.hash.random.DefaultHasher

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2901:4-2901:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3103:4-3103:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::clear]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::clear"]
axiom alloc.vec.Vec.clear
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3160:4-3160:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [alloc::vec::{alloc::vec::Vec<T>}::resize_with]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3255:4-3257:24
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::resize_with]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::resize_with"]
axiom alloc.vec.Vec.resize_with
  {T : Type} (A : Type) {F : Type} (coreopsfunctionFnMutFTupleTInst :
  core.ops.function.FnMut F Unit T) :
  alloc.vec.Vec T → Std.Usize → F → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::dedup]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3802:4-3802:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::dedup]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::dedup"]
axiom alloc.vec.Vec.dedup
  {T : Type} (A : Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::hash::Hash for alloc::vec::Vec<T>}::hash]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3965:4-3965:44
    Name pattern: [alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash]
    Visibility: public -/
@[rust_fun "alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash"]
axiom alloc.vec.Vec.Insts.CoreHashHash.hash
  {T : Type} (A : Type) {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  alloc.vec.Vec T → H → Result H

/-- [alloc::vec::{impl core::iter::traits::collect::Extend<T> for alloc::vec::Vec<T>}::extend]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4107:4-4107:60
    Name pattern: [alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend"]
axiom alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend.extend
  {T : Type} (A : Type) {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorInst :
  core.iter.traits.collect.IntoIterator I T Clause0_IntoIter) :
  alloc.vec.Vec T → I → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::default::Default for alloc::vec::Vec<T>}::default]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4417:4-4417:26
    Name pattern: [alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default"]
axiom alloc.vec.Vec.Insts.CoreDefaultDefault.default
  (T : Type) : Result (alloc.vec.Vec T)

/-- [merc_io::progress::{merc_io::progress::TimeProgress<T>}::print]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/io/src/progress.rs', lines 38:4-38:34
    Name pattern: [merc_io::progress::{merc_io::progress::TimeProgress<@T>}::print]
    Visibility: public -/
@[rust_fun "merc_io::progress::{merc_io::progress::TimeProgress<@T>}::print"]
axiom merc_io.progress.TimeProgress.print
  {T : Type} : merc_io.progress.TimeProgress T → T → Result Unit

/-- [merc_lts::lts::{impl core::clone::Clone for merc_lts::lts::Transition}::clone]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 132:9-132:14
    Name pattern: [merc_lts::lts::{core::clone::Clone<merc_lts::lts::Transition>}::clone]
    Visibility: public -/
@[rust_fun
  "merc_lts::lts::{core::clone::Clone<merc_lts::lts::Transition>}::clone"]
axiom merc_lts.lts.Transition.Insts.CoreCloneClone.clone
  : merc_lts.lts.Transition → Result merc_lts.lts.Transition

/-- [merc_lts::lts::{impl core::cmp::PartialEq<merc_lts::lts::Transition> for merc_lts::lts::Transition}::eq]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 132:23-132:32
    Name pattern: [merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>}::eq]
    Visibility: public -/
@[rust_fun
  "merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>}::eq"]
axiom merc_lts.lts.Transition.Insts.CoreCmpPartialEqTransition.eq
  : merc_lts.lts.Transition → merc_lts.lts.Transition → Result Bool

/-- [merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/block_partition.rs', lines 532:4-532:31
    Name pattern: [merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent] -/
@[rust_fun
  "merc_reduction::block_partition::{merc_reduction::block_partition::Block}::assert_consistent"]
axiom merc_reduction.block_partition.Block.assert_consistent
  : merc_reduction.block_partition.Block → Result Unit

/-- [merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/block_partition.rs', lines 955:4-955:39
    Name pattern: [merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent] -/
@[rust_fun
  "merc_reduction::block_partition::{merc_reduction::block_partition::BlockPartition}::assert_consistent"]
axiom merc_reduction.block_partition.BlockPartition.assert_consistent
  : merc_reduction.block_partition.BlockPartition → Result Bool

/-- [merc_utilities::timing::{merc_utilities::timing::Timing}::measure]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/timing.rs', lines 37:4-39:25
    Name pattern: [merc_utilities::timing::{merc_utilities::timing::Timing}::measure]
    Visibility: public -/
@[rust_fun "merc_utilities::timing::{merc_utilities::timing::Timing}::measure"]
axiom merc_utilities.timing.Timing.measure
  {F : Type} {O : Type} (coreopsfunctionFnOnceFTupleOInst :
  core.ops.function.FnOnce F Unit O) :
  merc_utilities.timing.Timing → Str → F → Result O

/-- [rustc_hash::{impl core::default::Default for rustc_hash::FxBuildHasher}::default]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 344:44-344:51
    Name pattern: [rustc_hash::{core::default::Default<rustc_hash::FxBuildHasher>}::default]
    Visibility: public -/
@[rust_fun
  "rustc_hash::{core::default::Default<rustc_hash::FxBuildHasher>}::default"]
axiom rustc_hash.FxBuildHasher.Insts.CoreDefaultDefault.default
  : Result rustc_hash.FxBuildHasher

/-- [rustc_hash::{impl core::hash::BuildHasher<rustc_hash::FxHasher> for rustc_hash::FxBuildHasher}::build_hasher]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 350:4-350:38
    Name pattern: [rustc_hash::{core::hash::BuildHasher<rustc_hash::FxBuildHasher, rustc_hash::FxHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "rustc_hash::{core::hash::BuildHasher<rustc_hash::FxBuildHasher, rustc_hash::FxHasher>}::build_hasher"]
axiom rustc_hash.FxBuildHasher.Insts.CoreHashBuildHasherFxHasher.build_hasher
  : rustc_hash.FxBuildHasher → Result rustc_hash.FxHasher

/-- [rustc_hash::{impl core::hash::Hasher for rustc_hash::FxHasher}::finish]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 192:4-192:27
    Name pattern: [rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::finish]
    Visibility: public -/
@[rust_fun "rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::finish"]
axiom rustc_hash.FxHasher.Insts.CoreHashHasher.finish
  : rustc_hash.FxHasher → Result Std.U64

/-- [rustc_hash::{impl core::hash::Hasher for rustc_hash::FxHasher}::write]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 130:4-130:37
    Name pattern: [rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::write]
    Visibility: public -/
@[rust_fun "rustc_hash::{core::hash::Hasher<rustc_hash::FxHasher>}::write"]
axiom rustc_hash.FxHasher.Insts.CoreHashHasher.write
  : rustc_hash.FxHasher → Slice Std.U8 → Result rustc_hash.FxHasher

/-- [merc_utilities::tagged_index::{impl core::hash::Hash for merc_utilities::tagged_index::TagIndex<T, Tag>}::hash]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 83:4-83:55
    Name pattern: [merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash.hash
  {T : Type} {Tag : Type} {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  merc_utilities.tagged_index.TagIndex T Tag → H → Result H

/-- [merc_reduction::signature_refinement::new_worklist_progress]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 1655:0-1655:58
    Name pattern: [merc_reduction::signature_refinement::new_worklist_progress] -/
@[rust_fun "merc_reduction::signature_refinement::new_worklist_progress"]
axiom merc_reduction.signature_refinement.new_worklist_progress
  : Result (merc_io.progress.TimeProgress (Std.Usize × Std.Usize))

