-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import MercVerified.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open verified

/-- [core::borrow::{core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- [core::hash::impls::{core::hash::Hash for usize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<usize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<usize>}::hash"]
axiom Usize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Usize → H → Result H

/-- [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::collect]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::collect"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
  {B : Type} {I : Type} {F : Type} {B1 : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator B1 B) :
  core.iter.adapters.map.Map I F → Result B1

/-- [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::sum]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::sum]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::sum"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.sum
  {B : Type} {I : Type} {F : Type} {S : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (traitsaccumSumInst :
  core.iter.traits.accum.Sum S B) :
  core.iter.adapters.map.Map I F → Result S

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::sum]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::sum]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::sum"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.sum
  {A : Type} {S : Type} (StepInst : core.iter.range.Step A) (traitsaccumSumInst
  : core.iter.traits.accum.Sum S A) :
  core.ops.range.Range A → Result S

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::collect]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::collect]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::collect"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.collect
  {A : Type} {B : Type} (StepInst : core.iter.range.Step A)
  (traitscollectFromIteratorInst : core.iter.traits.collect.FromIterator B A) :
  core.ops.range.Range A → Result B

/-- [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::map]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 852:0-852:40
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::map]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::map"]
axiom core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.map
  {A : Type} {B : Type} {F : Type} (StepInst : core.iter.range.Step A)
  (opsfunctionFnMutFTupleABInst : core.ops.function.FnMut F A B) :
  core.ops.range.Range A → F → Result (core.iter.adapters.map.Map
    (core.ops.range.Range A) F)

/-- [core::iter::traits::accum::{core::iter::traits::accum::Sum<usize> for usize}::sum]:
    Source: '/rustc/library/core/src/iter/traits/accum.rs', lines 49:12-49:59
    Name pattern: [core::iter::traits::accum::{core::iter::traits::accum::Sum<usize, usize>}::sum]
    Visibility: public -/
@[rust_fun
  "core::iter::traits::accum::{core::iter::traits::accum::Sum<usize, usize>}::sum"]
axiom Usize.Insts.CoreIterTraitsAccumSumUsize.sum
  {I : Type} (iteratorIteratorIUsizeInst : core.iter.traits.iterator.Iterator I
  Std.Usize) :
  I → Result Std.Usize

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 789:4-792:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::sum]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 3653:4-3656:27
    Name pattern: [core::iter::traits::iterator::Iterator::sum]
    Visibility: public -/
@[rust_fun "core::iter::traits::iterator::Iterator::sum"]
axiom core.iter.traits.iterator.Iterator.sum.default
  {Self : Type} {S : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) (accumSumInst :
  core.iter.traits.accum.Sum S Clause0_Item) :
  Self → Result S

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::values]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 543:4-543:44
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::values]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::values"]
axiom std.collections.hash.map.HashMap.values
  {K : Type} {V : Type} {S : Type} {A : Type} :
  std.collections.hash.map.HashMap K V S A → Result
    (std.collections.hash.map.Values K V)

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::len]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 690:4-690:30
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::len]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::len"]
axiom std.collections.hash.map.HashMap.len
  {K : Type} {V : Type} {S : Type} {A : Type} :
  std.collections.hash.map.HashMap K V S A → Result Std.Usize

/-- [std::collections::hash::map::{std::collections::hash::map::HashMap<K, V, S, A>}::get]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 997:4-1000:21
    Name pattern: [std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{std::collections::hash::map::HashMap<@K, @V, @S, @A>}::get"]
axiom std.collections.hash.map.HashMap.get
  {K : Type} {V : Type} {S : Type} {A : Type} {Q : Type} {Clause2_Hasher :
  Type} (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corehashBuildHasherInst : core.hash.BuildHasher S Clause2_Hasher)
  (coreborrowBorrowInst : core.borrow.Borrow K Q) (corehashHashInst1 :
  core.hash.Hash Q) (corecmpEqInst1 : core.cmp.Eq Q) :
  std.collections.hash.map.HashMap K V S A → Q → Result (Option V)

/-- [std::collections::hash::map::{core::clone::Clone for std::collections::hash::map::HashMap<K, V, S, A>}::clone]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1397:4-1397:27
    Name pattern: [std::collections::hash::map::{core::clone::Clone<std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::clone]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::clone::Clone<std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::clone"]
axiom std.collections.hash.map.HashMap.Insts.CoreCloneClone.clone
  {K : Type} {V : Type} {S : Type} {A : Type} (corecloneCloneInst :
  core.clone.Clone K) (corecloneCloneInst1 : core.clone.Clone V)
  (corecloneCloneInst2 : core.clone.Clone S) (corecloneCloneInst3 :
  core.clone.Clone A) :
  std.collections.hash.map.HashMap K V S A → Result
    (std.collections.hash.map.HashMap K V S A)

/-- [std::collections::hash::map::{core::cmp::PartialEq<std::collections::hash::map::HashMap<K, V, S, A>> for std::collections::hash::map::HashMap<K, V, S, A>}::eq]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1415:4-1415:53
    Name pattern: [std::collections::hash::map::{core::cmp::PartialEq<std::collections::hash::map::HashMap<@K, @V, @S, @A>, std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::eq]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::cmp::PartialEq<std::collections::hash::map::HashMap<@K, @V, @S, @A>, std::collections::hash::map::HashMap<@K, @V, @S, @A>>}::eq"]
axiom std.collections.hash.map.HashMap.Insts.CoreCmpPartialEqHashMap.eq
  {K : Type} {V : Type} {S : Type} {A : Type} {Clause3_Hasher : Type}
  (corecmpEqInst : core.cmp.Eq K) (corehashHashInst : core.hash.Hash K)
  (corecmpPartialEqInst : core.cmp.PartialEq V V) (corehashBuildHasherInst :
  core.hash.BuildHasher S Clause3_Hasher) :
  std.collections.hash.map.HashMap K V S A → std.collections.hash.map.HashMap
    K V S A → Result Bool

/-- [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}::next]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2236:4-2236:39
    Name pattern: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::next]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::next"]
axiom
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.next
  {K : Type} {V : Type} :
  std.collections.hash.map.Values K V → Result ((Option V) ×
    (std.collections.hash.map.Values K V))

/-- [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}::sum]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2232:0-2232:44
    Name pattern: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::sum]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::sum"]
axiom
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.sum
  {K : Type} {V : Type} {S : Type} (coreitertraitsaccumSumSSharedAVInst :
  core.iter.traits.accum.Sum S V) :
  std.collections.hash.map.Values K V → Result S

/-- [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}::collect]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2232:0-2232:44
    Name pattern: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::collect]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::collect"]
axiom
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.collect
  {K : Type} {V : Type} {B : Type}
  (coreitertraitscollectFromIteratorBSharedAVInst :
  core.iter.traits.collect.FromIterator B V) :
  std.collections.hash.map.Values K V → Result B

/-- [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}::map]:
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2232:0-2232:44
    Name pattern: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::map]
    Visibility: public -/
@[rust_fun
  "std::collections::hash::map::{core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>}::map"]
axiom
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.map
  {K : Type} {V : Type} {B : Type} {F : Type}
  (coreopsfunctionFnMutFTupleSharedAVBInst : core.ops.function.FnMut F V B) :
  std.collections.hash.map.Values K V → F → Result
    (core.iter.adapters.map.Map (std.collections.hash.map.Values K V) F)

/-- [std::hash::random::{core::clone::Clone for std::hash::random::RandomState}::clone]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 34:9-34:14
    Name pattern: [std::hash::random::{core::clone::Clone<std::hash::random::RandomState>}::clone]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::clone::Clone<std::hash::random::RandomState>}::clone"]
axiom std.hash.random.RandomState.Insts.CoreCloneClone.clone
  : std.hash.random.RandomState → Result std.hash.random.RandomState

/-- [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}::finish]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 140:4-140:27
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::finish"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  : std.hash.random.DefaultHasher → Result Std.U64

/-- [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}::write]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 130:4-130:35
    Name pattern: [std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::Hasher<std::hash::random::DefaultHasher>}::write"]
axiom std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
  :
  std.hash.random.DefaultHasher → Slice Std.U8 → Result
    std.hash.random.DefaultHasher

/-- [std::hash::random::{core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}::build_hasher]:
    Source: '/rustc/library/std/src/hash/random.rs', lines 83:4-83:43
    Name pattern: [std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher]
    Visibility: public -/
@[rust_fun
  "std::hash::random::{core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>}::build_hasher"]
axiom
  std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
  : std.hash.random.RandomState → Result std.hash.random.DefaultHasher

/-- [merc_lts::lts::{core::clone::Clone for merc_lts::lts::Transition}::clone]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 115:9-115:14
    Name pattern: [merc_lts::lts::{core::clone::Clone<merc_lts::lts::Transition>}::clone]
    Visibility: public -/
@[rust_fun
  "merc_lts::lts::{core::clone::Clone<merc_lts::lts::Transition>}::clone"]
axiom merc_lts.lts.Transition.Insts.CoreCloneClone.clone
  : merc_lts.lts.Transition → Result merc_lts.lts.Transition

/-- [merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition> for merc_lts::lts::Transition}::eq]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 115:23-115:32
    Name pattern: [merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>}::eq]
    Visibility: public -/
@[rust_fun
  "merc_lts::lts::{core::cmp::PartialEq<merc_lts::lts::Transition, merc_lts::lts::Transition>}::eq"]
axiom merc_lts.lts.Transition.Insts.CoreCmpPartialEqTransition.eq
  : merc_lts.lts.Transition → merc_lts.lts.Transition → Result Bool

/-- [merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<T, Tag>> for merc_utilities::tagged_index::TagIndex<T, Tag>}::eq]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 59:4-59:38
    Name pattern: [merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::eq]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::eq"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEqTagIndex.eq
  {T : Type} {Tag : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  merc_utilities.tagged_index.TagIndex T Tag →
    merc_utilities.tagged_index.TagIndex T Tag → Result Bool

/-- [merc_utilities::tagged_index::{core::cmp::Eq for merc_utilities::tagged_index::TagIndex<T, Tag>}::assert_receiver_is_total_eq]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 56:0-56:47
    Name pattern: [merc_utilities::tagged_index::{core::cmp::Eq<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::assert_receiver_is_total_eq]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::cmp::Eq<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::assert_receiver_is_total_eq"]
axiom
  merc_utilities.tagged_index.TagIndex.Insts.CoreCmpEq.assert_receiver_is_total_eq
  {T : Type} {Tag : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  merc_utilities.tagged_index.TagIndex T Tag → Result Unit

/-- [merc_utilities::tagged_index::{core::hash::Hash for merc_utilities::tagged_index::TagIndex<T, Tag>}::hash]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 77:4-77:55
    Name pattern: [merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::hash::Hash<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::hash"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreHashHash.hash
  {T : Type} {Tag : Type} {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  merc_utilities.tagged_index.TagIndex T Tag → H → Result H

/-- [merc_utilities::tagged_index::{core::clone::Clone for merc_utilities::tagged_index::TagIndex<T, Tag>}::clone]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 83:4-83:27
    Name pattern: [merc_utilities::tagged_index::{core::clone::Clone<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::clone]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::clone::Clone<merc_utilities::tagged_index::TagIndex<@T, @Tag>>}::clone"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreCloneClone.clone
  {T : Type} {Tag : Type} (corecloneCloneInst : core.clone.Clone T) :
  merc_utilities.tagged_index.TagIndex T Tag → Result
    (merc_utilities.tagged_index.TagIndex T Tag)

/-- [merc_utilities::tagged_index::{core::cmp::PartialEq<T> for merc_utilities::tagged_index::TagIndex<T, Tag>}::eq]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 92:4-92:35
    Name pattern: [merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, @T>}::eq]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{core::cmp::PartialEq<merc_utilities::tagged_index::TagIndex<@T, @Tag>, @T>}::eq"]
axiom merc_utilities.tagged_index.TagIndex.Insts.CoreCmpPartialEq.eq
  {T : Type} {Tag : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  merc_utilities.tagged_index.TagIndex T Tag → T → Result Bool

/-- [merc_utilities::tagged_index::{merc_utilities::tagged_index::TagIndex<T, Tag>}::new]:
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 106:4-106:32
    Name pattern: [merc_utilities::tagged_index::{merc_utilities::tagged_index::TagIndex<@T, @Tag>}::new]
    Visibility: public -/
@[rust_fun
  "merc_utilities::tagged_index::{merc_utilities::tagged_index::TagIndex<@T, @Tag>}::new"]
axiom merc_utilities.tagged_index.TagIndex.new
  {T : Type} (Tag : Type) :
  T → Result (merc_utilities.tagged_index.TagIndex T Tag)

