-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: function definitions
import Aeneas
import MercVerified.Code.Types
import MercVerified.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace verified

/-- Trait implementation: [core::borrow::{core::borrow::Borrow<T> for T}]
    Source: '/rustc/library/core/src/borrow.rs', lines 212:0-212:37
    Name pattern: [core::borrow::Borrow<@T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<@T, @T>"]
def core.borrow.Borrow.Blanket (T : Type) : core.borrow.Borrow T T := {
  borrow := core.borrow.Borrow.Blanket.borrow
}

/-- Trait implementation: [core::hash::impls::{core::hash::Hash for usize}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 810:12-810:29
    Name pattern: [core::hash::Hash<usize>] -/
@[reducible, rust_trait_impl "core::hash::Hash<usize>"]
def Usize.Insts.CoreHashHash : core.hash.Hash Std.Usize := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    Usize.Insts.CoreHashHash.hash HasherInst
}

/-- Trait implementation: [core::iter::traits::accum::{core::iter::traits::accum::Sum<usize> for usize}]
    Source: '/rustc/library/core/src/iter/traits/accum.rs', lines 48:8-48:23
    Name pattern: [core::iter::traits::accum::Sum<usize, usize>] -/
@[reducible, rust_trait_impl "core::iter::traits::accum::Sum<usize, usize>"]
def Usize.Insts.CoreIterTraitsAccumSumUsize : core.iter.traits.accum.Sum
  Std.Usize Std.Usize := {
  sum := fun {I : Type} (iteratorIteratorPUsizeInst :
    core.iter.traits.iterator.Iterator I Std.Usize) =>
    Usize.Insts.CoreIterTraitsAccumSumUsize.sum iteratorIteratorPUsizeInst
}

/-- Trait implementation: [std::collections::hash::map::{core::iter::traits::iterator::Iterator<&'a (V)> for std::collections::hash::map::Values<'a, K, V>}]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 2232:0-2232:44
    Name pattern: [core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<std::collections::hash::map::Values<'a, @K, @V>, &'a @V>"]
def
  std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV
  (K : Type) (V : Type) : core.iter.traits.iterator.Iterator
  (std.collections.hash.map.Values K V) V := {
  next :=
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.next
  step_by := fun self steps =>
    if steps.val = 0 then .fail .panic else ok ⟨ self, steps ⟩
  enumerate := fun self => .ok { iter := self, count := 0#usize }
  take := fun self n => ok ⟨ self, n ⟩
}

/-- Trait implementation: [std::hash::random::{core::clone::Clone for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 34:9-34:14
    Name pattern: [core::clone::Clone<std::hash::random::RandomState>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<std::hash::random::RandomState>"]
def std.hash.random.RandomState.Insts.CoreCloneClone : core.clone.Clone
  std.hash.random.RandomState := {
  clone := std.hash.random.RandomState.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 125:0-125:29
    Name pattern: [core::hash::Hasher<std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::Hasher<std::hash::random::DefaultHasher>"]
def std.hash.random.DefaultHasher.Insts.CoreHashHasher : core.hash.Hasher
  std.hash.random.DefaultHasher := {
  finish := std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  write := std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
}

/-- Trait implementation: [std::hash::random::{core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 80:0-80:32
    Name pattern: [core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>"]
def std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher :
  core.hash.BuildHasher std.hash.random.RandomState
  std.hash.random.DefaultHasher := {
  HasherInst := std.hash.random.DefaultHasher.Insts.CoreHashHasher
  build_hasher :=
    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
}

/-- [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::Transition}::clone]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:9-9:14
    Visibility: public -/
def simple_labelled_transition_system.Transition.Insts.CoreCloneClone.clone
  (self : simple_labelled_transition_system.Transition) :
  Result simple_labelled_transition_system.Transition
  := do
  let i ← lift (core.clone.impls.CloneUsize.clone self.label)
  let i1 ← lift (core.clone.impls.CloneUsize.clone self.«to»)
  ok { label := i, «to» := i1 }

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:9-9:14 -/
@[reducible]
def simple_labelled_transition_system.Transition.Insts.CoreCloneClone :
  core.clone.Clone simple_labelled_transition_system.Transition := {
  clone :=
    simple_labelled_transition_system.Transition.Insts.CoreCloneClone.clone
}

/-- [verified::simple_labelled_transition_system::{core::fmt::Debug for verified::simple_labelled_transition_system::Transition}::fmt]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:16-9:21
    Visibility: public -/
def simple_labelled_transition_system.Transition.Insts.CoreFmtDebug.fmt
  (self : simple_labelled_transition_system.Transition)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugUsize self.label
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.«to»
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Transition") (toStr
    "label") dyn (toStr "to") dyn1

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::fmt::Debug for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:16-9:21 -/
@[reducible]
def simple_labelled_transition_system.Transition.Insts.CoreFmtDebug :
  core.fmt.Debug simple_labelled_transition_system.Transition := {
  fmt := simple_labelled_transition_system.Transition.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::marker::StructuralPartialEq for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:23-9:32 -/
@[reducible]
def
  simple_labelled_transition_system.Transition.Insts.CoreMarkerStructuralPartialEq
  : core.marker.StructuralPartialEq
  simple_labelled_transition_system.Transition := {
}

/-- [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::Transition> for verified::simple_labelled_transition_system::Transition}::eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:23-9:32
    Visibility: public -/
def
  simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition.eq
  (self : simple_labelled_transition_system.Transition)
  (other : simple_labelled_transition_system.Transition) :
  Result Bool
  := do
  if self.label = other.label
  then ok (self.«to» = other.«to»)
  else ok false

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::Transition> for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:23-9:32 -/
@[reducible]
def
  simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition
  : core.cmp.PartialEq simple_labelled_transition_system.Transition
  simple_labelled_transition_system.Transition := {
  eq :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition.eq
}

/-- [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::Transition}::assert_receiver_is_total_eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:34-9:36
    Visibility: public -/
def
  simple_labelled_transition_system.Transition.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : simple_labelled_transition_system.Transition) : Result Unit := do
  ok ()

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:34-9:36 -/
@[reducible]
def simple_labelled_transition_system.Transition.Insts.CoreCmpEq : core.cmp.Eq
  simple_labelled_transition_system.Transition := {
  partialEqInst :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition
  assert_receiver_is_total_eq :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [verified::simple_labelled_transition_system::{core::cmp::PartialOrd<verified::simple_labelled_transition_system::Transition> for verified::simple_labelled_transition_system::Transition}::partial_cmp]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:38-9:48
    Visibility: public -/
def
  simple_labelled_transition_system.Transition.Insts.CoreCmpPartialOrdTransition.partial_cmp
  (self : simple_labelled_transition_system.Transition)
  (other : simple_labelled_transition_system.Transition) :
  Result (Option Ordering)
  := do
  let o ←
    lift (core.cmp.impls.PartialOrdUsize.partial_cmp self.label other.label)
  match o with
  | none => ok none
  | some o1 =>
    match o1 with
    | Ordering.lt => ok o
    | Ordering.eq =>
      ok (core.cmp.impls.PartialOrdUsize.partial_cmp self.«to» other.«to»)
    | Ordering.gt => ok o

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::PartialOrd<verified::simple_labelled_transition_system::Transition> for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:38-9:48 -/
@[reducible]
def
  simple_labelled_transition_system.Transition.Insts.CoreCmpPartialOrdTransition
  : core.cmp.PartialOrd simple_labelled_transition_system.Transition
  simple_labelled_transition_system.Transition := {
  partialEqInst :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition
  partial_cmp :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpPartialOrdTransition.partial_cmp
}

/-- [verified::simple_labelled_transition_system::{core::cmp::Ord for verified::simple_labelled_transition_system::Transition}::cmp]:
    Source: 'src/simple_labelled_transition_system.rs', lines 9:50-9:53
    Visibility: public -/
def simple_labelled_transition_system.Transition.Insts.CoreCmpOrd.cmp
  (self : simple_labelled_transition_system.Transition)
  (other : simple_labelled_transition_system.Transition) :
  Result Ordering
  := do
  let o ← lift (core.cmp.impls.OrdUsize.cmp self.label other.label)
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq => ok (core.cmp.impls.OrdUsize.cmp self.«to» other.«to»)
  | Ordering.gt => ok Ordering.gt

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::Ord for verified::simple_labelled_transition_system::Transition}]
    Source: 'src/simple_labelled_transition_system.rs', lines 9:50-9:53 -/
@[reducible]
def simple_labelled_transition_system.Transition.Insts.CoreCmpOrd :
  core.cmp.Ord simple_labelled_transition_system.Transition := {
  eqInst := simple_labelled_transition_system.Transition.Insts.CoreCmpEq
  partialOrdInst :=
    simple_labelled_transition_system.Transition.Insts.CoreCmpPartialOrdTransition
  cmp := simple_labelled_transition_system.Transition.Insts.CoreCmpOrd.cmp
}

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::Transition}::new]:
    Source: 'src/simple_labelled_transition_system.rs', lines 17:4-19:5
    Visibility: public -/
def simple_labelled_transition_system.Transition.new
  (label : Std.Usize) (to1 : Std.Usize) :
  Result simple_labelled_transition_system.Transition
  := do
  ok { label, «to» := to1 }

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::marker::StructuralPartialEq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 29:9-29:18 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreMarkerStructuralPartialEq
  (Label : Type) : core.marker.StructuralPartialEq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
}

/-- [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 29:9-29:18
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem.eq
  {Label : Type} (corecmpPartialEqInst : core.cmp.PartialEq Label Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label)
  (other : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Bool
  := do
  let b ←
    std.collections.hash.map.HashMap.Insts.CoreCmpPartialEqHashMap.eq
      core.cmp.EqUsize Usize.Insts.CoreHashHash (core.cmp.PartialEqVec
      simple_labelled_transition_system.Transition.Insts.CoreCmpPartialEqTransition)
      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
      self.transitions other.transitions
  if b
  then
    let b1 ←
      alloc.vec.partial_eq.PartialEqVec.eq corecmpPartialEqInst self.labels
        other.labels
    if b1
    then ok (self.initial_state = other.initial_state)
    else ok false
  else ok false

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::PartialEq<verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>> for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 29:9-29:18 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem
  {Label : Type} (corecmpPartialEqInst : core.cmp.PartialEq Label Label) :
  core.cmp.PartialEq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label)
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  eq :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem.eq
    corecmpPartialEqInst
}

/-- [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::assert_receiver_is_total_eq]:
    Source: 'src/simple_labelled_transition_system.rs', lines 29:20-29:22
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq.assert_receiver_is_total_eq
  {Label : Type} (corecmpEqInst : core.cmp.Eq Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Unit
  := do
  ok ()

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::cmp::Eq for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 29:20-29:22 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq
  {Label : Type} (corecmpEqInst : core.cmp.Eq Label) : core.cmp.Eq
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  partialEqInst :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpPartialEqSimpleLabelledTransitionSystem
    corecmpEqInst.partialEqInst
  assert_receiver_is_total_eq :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCmpEq.assert_receiver_is_total_eq
    corecmpEqInst
}

/-- [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::clone]:
    Source: 'src/simple_labelled_transition_system.rs', lines 29:24-29:29
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone.clone
  {Label : Type} (corecloneCloneInst : core.clone.Clone Label)
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (simple_labelled_transition_system.SimpleLabelledTransitionSystem
    Label)
  := do
  let hm ←
    std.collections.hash.map.HashMap.Insts.CoreCloneClone.clone
      core.clone.CloneUsize (core.clone.CloneallocvecVec
      simple_labelled_transition_system.Transition.Insts.CoreCloneClone)
      std.hash.random.RandomState.Insts.CoreCloneClone
      core.core.clone.CloneGlobal self.transitions
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.labels
  let i ← lift (core.clone.impls.CloneUsize.clone self.initial_state)
  ok { transitions := hm, labels := v, initial_state := i }

/-- Trait implementation: [verified::simple_labelled_transition_system::{core::clone::Clone for verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 29:24-29:29 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone
  {Label : Type} (corecloneCloneInst : core.clone.Clone Label) :
  core.clone.Clone
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem Label) := {
  clone :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.Insts.CoreCloneClone.clone
    corecloneCloneInst
}

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::outgoing_transitions]:
    Source: 'src/simple_labelled_transition_system.rs', lines 42:4-47:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.outgoing_transitions
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) (state_index : Std.Usize) :
  Result (alloc.vec.Vec simple_labelled_transition_system.Transition)
  := do
  let o ←
    std.collections.hash.map.HashMap.get core.cmp.EqUsize
      Usize.Insts.CoreHashHash
      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
      (core.borrow.Borrow.Blanket Std.Usize) Usize.Insts.CoreHashHash
      core.cmp.EqUsize self.transitions state_index
  let v ← core.option.Option.expect o (toStr "State index out of bounds.")
  alloc.vec.CloneVec.clone
    simple_labelled_transition_system.Transition.Insts.CoreCloneClone v

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::initial_state_index]:
    Source: 'src/simple_labelled_transition_system.rs', lines 49:4-51:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.initial_state_index
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  ok self.initial_state

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_states]:
    Source: 'src/simple_labelled_transition_system.rs', lines 57:4-59:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_states
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  std.collections.hash.map.HashMap.len self.transitions

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::iter_states]:
    Source: 'src/simple_labelled_transition_system.rs', lines 53:4-55:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.iter_states
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (core.ops.range.Range Std.Usize)
  := do
  let i ←
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_states
      self
  ok { start := 0#usize, «end» := i }

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_labels]:
    Source: 'src/simple_labelled_transition_system.rs', lines 61:4-63:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_labels
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  ok (alloc.vec.Vec.len self.labels)

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnMut<(&'_ (alloc::vec::Vec<verified::simple_labelled_transition_system::Transition>)), usize> for verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}::call_mut]:
    Source: 'src/simple_labelled_transition_system.rs', lines 66:38-66:49 -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
  {Label : Type}
  (c :
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
  Label)
  (tupled_args : alloc.vec.Vec simple_labelled_transition_system.Transition) :
  Result (Std.Usize ×
    (simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
    Label))
  := do
  let i := alloc.vec.Vec.len tupled_args
  ok (i, c)

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnOnce<(&'_ (alloc::vec::Vec<verified::simple_labelled_transition_system::Transition>)), usize> for verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}::call_once]:
    Source: 'src/simple_labelled_transition_system.rs', lines 66:38-66:49 -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize.call_once
  {Label : Type}
  (c :
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
  Label) (v : alloc.vec.Vec simple_labelled_transition_system.Transition) :
  Result Std.Usize
  := do
  let (i, _) ←
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
      c v
  ok i

/-- Trait implementation: [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnOnce<(&'_ (alloc::vec::Vec<verified::simple_labelled_transition_system::Transition>)), usize> for verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 66:38-66:49 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize
  (Label : Type) : core.ops.function.FnOnce
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
  Label) (alloc.vec.Vec simple_labelled_transition_system.Transition) Std.Usize
  := {
  call_once :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize.call_once
}

/-- Trait implementation: [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::{core::ops::function::FnMut<(&'_ (alloc::vec::Vec<verified::simple_labelled_transition_system::Transition>)), usize> for verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure<Label>}]
    Source: 'src/simple_labelled_transition_system.rs', lines 66:38-66:49 -/
@[reducible]
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
  (Label : Type) : core.ops.function.FnMut
  (simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
  Label) (alloc.vec.Vec simple_labelled_transition_system.Transition) Std.Usize
  := {
  FnOnceInst :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnOnceTupleSharedVecTransitionUsize
    Label
  call_mut :=
    simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize.call_mut
}

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions]:
    Source: 'src/simple_labelled_transition_system.rs', lines 65:4-67:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result Std.Usize
  := do
  let v ← std.collections.hash.map.HashMap.values self.transitions
  let m ←
    std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV.map
      (simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
      Label) v ()
  core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.sum
    (std.collections.hash.map.Values.Insts.CoreIterTraitsIteratorIteratorSharedAV
    Std.Usize (alloc.vec.Vec simple_labelled_transition_system.Transition))
    (simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure.Insts.CoreOpsFunctionFnMutTupleSharedVecTransitionUsize
    Label) Usize.Insts.CoreIterTraitsAccumSumUsize m

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::labels]:
    Source: 'src/simple_labelled_transition_system.rs', lines 69:4-71:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.impl.labels
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) :
  Result (Slice Label)
  := do
  alloc.vec.Vec.index (core.slice.index.SliceIndexRangeFromUsizeSlice Label)
    self.labels { start := 0#usize }

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::is_hidden_label]:
    Source: 'src/simple_labelled_transition_system.rs', lines 73:4-75:5
    Visibility: public -/
def
  simple_labelled_transition_system.SimpleLabelledTransitionSystem.is_hidden_label
  {Label : Type}
  (self : simple_labelled_transition_system.SimpleLabelledTransitionSystem
  Label) (label_index : Std.Usize) :
  Result Bool
  := do
  ok (label_index = 0#usize)

end verified
