-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [std::collections::hash::map::HashMap]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 247:0-252:1
    Name pattern: [std::collections::hash::map::HashMap]
    Visibility: public -/
@[rust_type "std::collections::hash::map::HashMap"]
axiom std.collections.hash.map.HashMap (K : Type) (V : Type) (S : Type) (A :
  Type) : Type

/-- [std::collections::hash::map::Values]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1710:0-1710:35
    Name pattern: [std::collections::hash::map::Values]
    Visibility: public -/
@[rust_type "std::collections::hash::map::Values"]
axiom std.collections.hash.map.Values (K : Type) (V : Type) : Type

/-- [std::hash::random::RandomState]
    Source: '/rustc/library/std/src/hash/random.rs', lines 35:0-35:22
    Name pattern: [std::hash::random::RandomState]
    Visibility: public -/
@[rust_type "std::hash::random::RandomState"]
axiom std.hash.random.RandomState : Type

/-- [std::hash::random::DefaultHasher]
    Source: '/rustc/library/std/src/hash/random.rs', lines 94:0-94:24
    Name pattern: [std::hash::random::DefaultHasher]
    Visibility: public -/
@[rust_type "std::hash::random::DefaultHasher"]
axiom std.hash.random.DefaultHasher : Type

/-- [merc_lts::labelled_transition_system::LabelledTransitionSystem]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/labelled_transition_system.rs', lines 29:0-29:42
    Name pattern: [merc_lts::labelled_transition_system::LabelledTransitionSystem]
    Visibility: public -/
@[rust_type "merc_lts::labelled_transition_system::LabelledTransitionSystem"]
axiom merc_lts.labelled_transition_system.LabelledTransitionSystem (Label :
  Type) : Type

/-- [merc_utilities::tagged_index::TagIndex]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 32:0-32:27
    Name pattern: [merc_utilities::tagged_index::TagIndex]
    Visibility: public -/
@[rust_type "merc_utilities::tagged_index::TagIndex"]
axiom merc_utilities.tagged_index.TagIndex (T : Type) (Tag : Type) : Type

