-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: type definitions
import Aeneas
import MercVerified.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace verified

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher]
    Visibility: public -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [merc_collections::indexed_partition::BlockTag]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/collections/src/indexed_partition.rs', lines 6:0-6:19
    Name pattern: [merc_collections::indexed_partition::BlockTag]
    Visibility: public -/
@[reducible, rust_type "merc_collections::indexed_partition::BlockTag"]
def merc_collections.indexed_partition.BlockTag := Unit

/-- [merc_lts::lts::StateTag]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 15:0-15:19
    Name pattern: [merc_lts::lts::StateTag]
    Visibility: public -/
@[reducible, rust_type "merc_lts::lts::StateTag"]
def merc_lts.lts.StateTag := Unit

/-- [merc_lts::lts::LabelTag]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 12:0-12:19
    Name pattern: [merc_lts::lts::LabelTag]
    Visibility: public -/
@[reducible, rust_type "merc_lts::lts::LabelTag"]
def merc_lts.lts.LabelTag := Unit

/-- [merc_lts::lts::Transition]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 104:0-104:21
    Name pattern: [merc_lts::lts::Transition]
    Visibility: public -/
@[rust_type "merc_lts::lts::Transition"]
structure merc_lts.lts.Transition where
  label : merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.LabelTag
  «to» : merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag

/-- Trait declaration: [merc_lts::lts::TransitionLabel]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 84:0-84:78
    Name pattern: [merc_lts::lts::TransitionLabel]
    Visibility: public -/
@[rust_trait "merc_lts::lts::TransitionLabel"
  (parentClauses := ["corecmpOrdInst", "corehashHashInst", "corecmpEqInst", "corecloneCloneInst", "corefmtDisplayInst", "corefmtDebugInst"])]
structure merc_lts.lts.TransitionLabel (Self : Type) where
  corecmpOrdInst : core.cmp.Ord Self
  corehashHashInst : core.hash.Hash Self
  corecmpEqInst : core.cmp.Eq Self
  corecloneCloneInst : core.clone.Clone Self
  corefmtDisplayInst : core.fmt.Display Self
  corefmtDebugInst : core.fmt.Debug Self
  tau_label : Result Self
  matches_label : Self → Str → Result Bool
  from_index : Std.Usize → Result Self

/-- Trait declaration: [merc_lts::lts::LTS]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/lts.rs', lines 28:0-28:13
    Name pattern: [merc_lts::lts::LTS]
    Visibility: public -/
@[rust_trait "merc_lts::lts::LTS" (parentClauses := ["TransitionLabelInst"])]
structure merc_lts.lts.LTS (Self : Type) (Self_Label : Type) where
  TransitionLabelInst : merc_lts.lts.TransitionLabel Self_Label
  initial_state_index : Self → Result (merc_utilities.tagged_index.TagIndex
    Std.Usize merc_lts.lts.StateTag)
  outgoing_transitions : Self → merc_utilities.tagged_index.TagIndex
    Std.Usize merc_lts.lts.StateTag → Result (alloc.vec.Vec
    merc_lts.lts.Transition)
  iter_states : Self → Result (alloc.vec.Vec
    (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag))
  num_of_states : Self → Result Std.Usize
  num_of_labels : Self → Result Std.Usize
  num_of_transitions : Self → Result Std.Usize
  labels : Self → Result (Slice Self_Label)
  is_hidden_label : Self → merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.LabelTag → Result Bool

/-- [merc_reduction::block_partition::Block]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/block_partition.rs', lines 514:0-514:16
    Name pattern: [merc_reduction::block_partition::Block]
    Visibility: public -/
@[rust_type "merc_reduction::block_partition::Block"]
structure merc_reduction.block_partition.Block where
  begin : Std.Usize
  marked_split : Std.Usize
  «end» : Std.Usize

/-- [merc_reduction::block_partition::BlockPartition]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/block_partition.rs', lines 16:0-16:25
    Name pattern: [merc_reduction::block_partition::BlockPartition]
    Visibility: public -/
@[rust_type "merc_reduction::block_partition::BlockPartition"]
structure merc_reduction.block_partition.BlockPartition where
  elements : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag)
  blocks : alloc.vec.Vec merc_reduction.block_partition.Block
  element_to_block : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex
    Std.Usize merc_collections.indexed_partition.BlockTag)
  element_offset : alloc.vec.Vec Std.Usize

/-- [merc_reduction::block_partition::BlockPartitionBuilder]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/block_partition.rs', lines 450:0-450:39
    Name pattern: [merc_reduction::block_partition::BlockPartitionBuilder] -/
@[rust_type "merc_reduction::block_partition::BlockPartitionBuilder"]
structure merc_reduction.block_partition.BlockPartitionBuilder where
  index_to_block : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex
    Std.Usize merc_collections.indexed_partition.BlockTag)
  block_sizes : alloc.vec.Vec Std.Usize
  old_elements : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag)

/-- Trait declaration: [merc_reduction::partition::Partition]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/partition.rs', lines 10:0-10:19
    Name pattern: [merc_reduction::partition::Partition]
    Visibility: public -/
@[rust_trait "merc_reduction::partition::Partition"]
structure merc_reduction.partition.Partition (Self : Type) where
  block_number : Self → merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag → Result (merc_utilities.tagged_index.TagIndex
    Std.Usize merc_collections.indexed_partition.BlockTag)
  num_of_blocks : Self → Result Std.Usize
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool

/-- [merc_reduction::signatures::Signature]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signatures.rs', lines 26:0-26:24
    Name pattern: [merc_reduction::signatures::Signature]
    Visibility: public -/
@[reducible, rust_type "merc_reduction::signatures::Signature"]
def merc_reduction.signatures.Signature :=
  Slice ((merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.LabelTag)
  × (merc_utilities.tagged_index.TagIndex Std.Usize
  merc_collections.indexed_partition.BlockTag))

/-- [merc_reduction::signature_refinement::WorklistContext]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 629:0-629:28
    Name pattern: [merc_reduction::signature_refinement::WorklistContext] -/
@[rust_type "merc_reduction::signature_refinement::WorklistContext"]
structure merc_reduction.signature_refinement.WorklistContext (F : Type) (G :
  Type) where
  partition : merc_reduction.block_partition.BlockPartition
  worklist : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_collections.indexed_partition.BlockTag)
  states : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag)
  builder : alloc.vec.Vec ((merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.LabelTag) × (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_collections.indexed_partition.BlockTag))
  split_builder : merc_reduction.block_partition.BlockPartitionBuilder
  state_to_key : alloc.vec.Vec (merc_utilities.tagged_index.TagIndex Std.Usize
    merc_collections.indexed_partition.BlockTag)
  signature : F
  renumber : G

/-- [merc_reduction::signature_refinement::signature_refinement::{closure}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 758:50-758:52
    Name pattern: [merc_reduction::signature_refinement::signature_refinement::closure] -/
@[reducible, rust_type
  "merc_reduction::signature_refinement::signature_refinement::closure"]
def merc_reduction.signature_refinement.signature_refinement.closure (F : Type)
  (G : Type) (L : Type) (Clause2_Label : Type) (BRANCHING : Bool) :=
Unit

/-- [merc_reduction::signature_refinement::strong_bisim_sigref::{closure}::{closure#1}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 63:12-63:18
    Name pattern: [merc_reduction::signature_refinement::strong_bisim_sigref::closure::closure#1] -/
@[reducible, rust_type
  "merc_reduction::signature_refinement::strong_bisim_sigref::closure::closure#1"]
def merc_reduction.signature_refinement.strong_bisim_sigref.closure.closure_1
  (L : Type) (Clause0_Label : Type) :=
Unit

/-- [merc_reduction::signature_refinement::strong_bisim_sigref::{closure}::{closure}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 60:12-60:48
    Name pattern: [merc_reduction::signature_refinement::strong_bisim_sigref::closure::closure] -/
@[reducible, rust_type
  "merc_reduction::signature_refinement::strong_bisim_sigref::closure::closure"]
def merc_reduction.signature_refinement.strong_bisim_sigref.closure.closure (L
  : Type) (Clause0_Label : Type) :=
  L

/-- [merc_reduction::signature_refinement::strong_bisim_sigref::{closure}]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/reduction/src/signature_refinement.rs', lines 56:48-56:50
    Name pattern: [merc_reduction::signature_refinement::strong_bisim_sigref::closure] -/
@[rust_type
  "merc_reduction::signature_refinement::strong_bisim_sigref::closure"]
def merc_reduction.signature_refinement.strong_bisim_sigref.closure (L : Type)
  (Clause0_Label : Type) :=
  L × merc_lts.incoming_transitions.IncomingTransitions

/-- [rustc_hash::FxBuildHasher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 346:0-346:24
    Name pattern: [rustc_hash::FxBuildHasher]
    Visibility: public -/
@[reducible, rust_type "rustc_hash::FxBuildHasher"]
def rustc_hash.FxBuildHasher := Unit

mutual

/-- [verified::list::Link]
    Source: 'src/list.rs', lines 8:0-11:1 -/
@[discriminant isize]
inductive list.Link (T : Type) where
| Empty : list.Link T
| More : list.Node T → list.Link T

/-- [verified::list::Node]
    Source: 'src/list.rs', lines 14:0-17:1 -/
inductive list.Node (T : Type) where
| mk : T → list.Link T → list.Node T

end

def list.Node.elem {T : Type} (x : list.Node T) :=
  match x with | list.Node.mk x1 _ => x1

def list.Node.next {T : Type} (x : list.Node T) :=
  match x with | list.Node.mk _ x1 => x1

@[simp]
theorem list.Node.elem._simpLemma_ {T : Type} (elem : T) (next : list.Link T) :
  (list.Node.mk elem next).elem = elem := by rfl

@[simp]
theorem list.Node.next._simpLemma_ {T : Type} (elem : T) (next : list.Link T) :
  (list.Node.mk elem next).next = next := by rfl

/-- [verified::list::List]
    Source: 'src/list.rs', lines 3:0-5:1
    Visibility: public -/
structure list.List (T : Type) where
  head : list.Link T

/-- [verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem]
    Source: 'src/simple_labelled_transition_system.rs', lines 19:0-28:1
    Visibility: public -/
structure simple_labelled_transition_system.SimpleLabelledTransitionSystem
  (Label : Type) where
  transitions : std.collections.hash.map.HashMap
    (merc_utilities.tagged_index.TagIndex Std.Usize merc_lts.lts.StateTag)
    (alloc.vec.Vec merc_lts.lts.Transition) std.hash.random.RandomState Global
  labels : alloc.vec.Vec Label
  initial_state : merc_utilities.tagged_index.TagIndex Std.Usize
    merc_lts.lts.StateTag

end verified
