-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: type definitions
import Aeneas
import MercVerified.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace verified

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher]
    Visibility: public -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [verified::simple_labelled_transition_system::Transition]
    Source: 'src/simple_labelled_transition_system.rs', lines 10:0-13:1
    Visibility: public -/
structure simple_labelled_transition_system.Transition where
  label : Std.Usize
  «to» : Std.Usize

/-- [verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem]
    Source: 'src/simple_labelled_transition_system.rs', lines 30:0-39:1
    Visibility: public -/
structure simple_labelled_transition_system.SimpleLabelledTransitionSystem
  (Label : Type) where
  transitions : std.collections.hash.map.HashMap Std.Usize (alloc.vec.Vec
    simple_labelled_transition_system.Transition) std.hash.random.RandomState
    Global
  labels : alloc.vec.Vec Label
  initial_state : Std.Usize

/-- [verified::simple_labelled_transition_system::{verified::simple_labelled_transition_system::SimpleLabelledTransitionSystem<Label>}::num_of_transitions::closure]
    Source: 'src/simple_labelled_transition_system.rs', lines 66:38-66:49 -/
@[reducible]
def simple_labelled_transition_system.SimpleLabelledTransitionSystem.num_of_transitions.closure
  (Label : Type) :=
Unit

end verified
