-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verified]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::sync::atomic::private::Align8]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 270:4-270:24
    Name pattern: [core::sync::atomic::private::Align8]
    Visibility: public -/
@[rust_type "core::sync::atomic::private::Align8"]
axiom core.sync.atomic.private.Align8 (T : Type) : Type

/-- [std::collections::hash::map::HashMap]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 245:0-250:1
    Name pattern: [std::collections::hash::map::HashMap]
    Visibility: public -/
@[rust_type "std::collections::hash::map::HashMap"]
axiom std.collections.hash.map.HashMap (K : Type) (V : Type) (S : Type) (A :
  Type) : Type

/-- [std::collections::hash::map::Values]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1750:0-1750:35
    Name pattern: [std::collections::hash::map::Values]
    Visibility: public -/
@[rust_type "std::collections::hash::map::Values"]
axiom std.collections.hash.map.Values (K : Type) (V : Type) : Type

/-- [std::collections::hash::set::HashSet]
    Source: '/rustc/library/std/src/collections/hash/set.rs', lines 126:0-130:1
    Name pattern: [std::collections::hash::set::HashSet]
    Visibility: public -/
@[rust_type "std::collections::hash::set::HashSet"]
axiom std.collections.hash.set.HashSet (T : Type) (S : Type) (A : Type) : Type

/-- [std::hash::random::RandomState]
    Source: '/rustc/library/std/src/hash/random.rs', lines 35:0-35:22
    Name pattern: [std::hash::random::RandomState]
    Visibility: public -/
@[rust_type "std::hash::random::RandomState"]
axiom std.hash.random.RandomState : Type

/-- [std::hash::random::DefaultHasher]
    Source: '/rustc/library/std/src/hash/random.rs', lines 94:0-94:24
    Name pattern: [std::hash::random::DefaultHasher]
    Visibility: public -/
@[rust_type "std::hash::random::DefaultHasher"]
axiom std.hash.random.DefaultHasher : Type

/-- [merc_io::progress::TimeProgress]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/io/src/progress.rs', lines 9:0-9:26
    Name pattern: [merc_io::progress::TimeProgress]
    Visibility: public -/
@[rust_type "merc_io::progress::TimeProgress"]
axiom merc_io.progress.TimeProgress (T : Type) : Type

/-- [merc_lts::incoming_transitions::IncomingTransitions]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/lts/src/incoming_transitions.rs', lines 23:0-23:30
    Name pattern: [merc_lts::incoming_transitions::IncomingTransitions]
    Visibility: public -/
@[rust_type "merc_lts::incoming_transitions::IncomingTransitions"]
axiom merc_lts.incoming_transitions.IncomingTransitions : Type

/-- [merc_utilities::tagged_index::TagIndex]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/tagged_index.rs', lines 32:0-32:27
    Name pattern: [merc_utilities::tagged_index::TagIndex]
    Visibility: public -

Model of `TagIndex<T, Tag>`: a phantom-tagged wrapper around `T` (the `Tag`
parameter is erased at runtime in Rust). Giving it this concrete meaning makes
every tagged operation (construction, extraction, comparison, indexed access)
definitional arithmetic on the payload, which is what the array-level proofs of
the worklist loop need. `new`/`value`/`cmp`/indexing are still extern
operations, but they now act on real values. -/
def merc_utilities.tagged_index.TagIndex (T : Type) (Tag : Type) : Type := T

/-- [merc_utilities::timing::Timing]
    Source: '/home/mlaveaux/merc-verified/3rd-party/merc/crates/utilities/src/timing.rs', lines 12:0-12:17
    Name pattern: [merc_utilities::timing::Timing]
    Visibility: public -/
@[rust_type "merc_utilities::timing::Timing"]
axiom merc_utilities.timing.Timing : Type

/-- [rustc_hash::FxHasher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustc-hash-2.1.2/src/lib.rs', lines 63:0-63:19
    Name pattern: [rustc_hash::FxHasher]
    Visibility: public -/
@[rust_type "rustc_hash::FxHasher"]
axiom rustc_hash.FxHasher : Type

