name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
        
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Build charon
      run: make setup-charon
      working-directory: ./aeneas
      env:        
        RUSTC_WRAPPER: sccache

    - name: Install OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.3
        dune-cache: true

    - name: Install OCaml Dependencies
      run: opam install -y ppx_deriving visitors easy_logging zarith yojson core_unix odoc ocamlgraph menhir ocamlformat.0.27.0 unionFind zarith progress domainslib

    - name: Setup dune
      uses: ocaml-dune/setup-dune@v2
      steps: install-dune

    - name: Build aeneas
      run: make
      working-directory: ./aeneas

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Generate LLBC using Charon
      run: ./aeneas/charon/bin/charon cargo --preset=aeneas 
      working-directory: ./crate

    - name: Generate lean code using aeneas
      run: ./aeneas/bin/aeneas -split-files -backend=lean -dest=./MercVerified/code/ ./crate/test.llbc
      working-directory: ./aeneas

    - name: Install and build Lean
      uses: leanprover/lean-action@v1
